### ISSUE TITLE
`from lookerapi import LookerApi` throws error, should be `LookApi`?

### ISSUE THREAD

**Issue by willdougadams** [llooker/python_api_samples#23]
Got a chat from a gentleman trying these out, he was getting `cannot import name "LookerApi" from 'lookerapi'`.  Changing this to `from lookerapi import LookApi` got rid of the error and did not produce new errors.  Is this a change made to the lookerapi package?  If so we should update these examples to reflect that.

**Comment by nathanielaldon** [comment]
Had someone else seeing this, and using `from lookerapi import LookApi` instead worked to fix it!

**Comment by UnicornAriel1** [comment]
I have had this same issue. I believe LookerApi worked in version 3.0, but am now using 3.1. I was able to resolve using `LookApi`
